openapi: 3.1.0
info:
  version: 1.0.0
  title: AquaTrack App
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: This is a documentation of AquaTrack App
tags:
  - name: Auth
    description: Auth operations.
  - name: Users
    description: Users operations.
  - name: Water
    description: Operations to track the water the user drinks.
  - name: Water{id}
    description: Operations with glass.
servers:
  - url: http://localhost:4000
  - url: https://aqua-tracker-project-2-backend.onrender.com
paths:
  /users/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /users/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /users/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /users/current:
    get:
      $ref: ../swagger/paths/auth/current.yaml
  /users/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /users/send-reset-password-email:
    post:
      $ref: ../swagger/paths/auth/sendResetPasswordEmail.yaml
  /users/reset-password:
    post:
      $ref: ../swagger/paths/auth/resetPassword.yaml
  /users/get-google-url-code:
    post:
      $ref: ../swagger/paths/auth/getGoogleUrlCode.yaml
  /users/login-with-google:
    post:
      $ref: ../swagger/paths/auth/loginWithGoogle.yaml
  /users/count:
    get:
      $ref: ../swagger/paths/users/count.yaml
  /users/update:
    patch:
      $ref: ../swagger/paths/users/patchUserData.yaml
  /users/avatar:
    patch:
      $ref: ../swagger/paths/users/patchAvatar.yaml
  /water/add-water:
    post:
      $ref: ../swagger/paths/water/postAddWater.yaml
  /water/monthly:
    get:
      $ref: ../swagger/paths/water/getMonthly.yaml
  /water/daily:
    get:
      $ref: ../swagger/paths/water/getDaily.yaml
  /water/delete/{id}:
    delete:
      $ref: ../swagger/paths/water/{id}/delete.yaml
  /water/update-volume/{id}:
    patch:
      $ref: ../swagger/paths/water/{id}/patchUpdateVolume.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
