openapi: 3.1.0
info:
  version: 1.0.0
  title: AquaTrack App
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    This is a documentation of AquaTrack App
tags:
  - name: Auth
    description: Auth operations.
  - name: Users
    description: Users operations.
  - name: Water
    description: Operations to track the water the user drinks.
  - name: Water{id}
    description: Operations with glass.
servers:
  - url: <http://localhost:4000>
paths:
  /users/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
