openapi: 3.1.0
info:
  version: 1.0.0
  title: AquaTrack App
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    This is a documentation of AquaTrack App
tags:
  - name: AquaTrack
    description: Operations to track the water the user drinks.
  - name: Auth
    description: Auth operations.
servers:
  - url: <http://localhost:4000>
paths:
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
